[features]
seeds = false
skip-lint = false

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "localnet" 
cluster = "https://devnet.helius-rpc.com/?api-key=950a4580-589c-4df3-a058-6324bcd6181e"
wallet = "/home/chukky_/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


