"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EDITION_BUYER_INFO_ACCOUNT = exports.EDITION_ALLOWLIST = exports.EDITION_DISTRIBUTOR = exports.LAST_BID_PRICE = exports.TREASURY = exports.FEE_PAYER = exports.AUCTION_HOUSE = void 0;
exports.AUCTION_HOUSE = "auction_house";
exports.FEE_PAYER = "fee_payer";
exports.TREASURY = "treasury";
exports.LAST_BID_PRICE = "last_bid_price";
exports.EDITION_DISTRIBUTOR = "edition_distributor";
exports.EDITION_ALLOWLIST = "edition_allowlist";
exports.EDITION_BUYER_INFO_ACCOUNT = "edition_buyer_info_account";
