"use strict";
var _a, _b, _c, _d, _e, _f, _g, _h, _j, _k, _l, _m, _o, _p, _q, _r, _s, _t, _u, _v, _w, _x, _y, _z, _0, _1, _2, _3, _4;
Object.defineProperty(exports, "__esModule", { value: true });
const AuctionHouse_1 = require("idl/AuctionHouse");
const identity = (val) => val;
const ixMap = (_a = AuctionHouse_1.IDL.instructionsMap) !== null && _a !== void 0 ? _a : {};
const AppendEditionAllowlistMerkleRootsAccounts = ((_b = ixMap.appendEditionAllowlistMerkleRoots) !== null && _b !== void 0 ? _b : []).map(identity);
const BuyEditionV2Accounts = ((_c = ixMap.buyEditionV2) !== null && _c !== void 0 ? _c : []).map(identity);
const BuyV2Accounts = ((_d = ixMap.buyV2) !== null && _d !== void 0 ? _d : []).map(identity);
const CancelV2Accounts = ((_e = ixMap.cancelV2) !== null && _e !== void 0 ? _e : []).map(identity);
const ClearEditionAllowlistMerkleRootsAccounts = ((_f = ixMap.clearEditionAllowlistMerkleRoots) !== null && _f !== void 0 ? _f : []).map(identity);
const CloseEditionAllowlistSettingsAccountAccounts = ((_g = ixMap.closeEditionAllowlistSettingsAccount) !== null && _g !== void 0 ? _g : []).map(identity);
const CloseEditionDistributorAccounts = ((_h = ixMap.closeEditionDistributor) !== null && _h !== void 0 ? _h : []).map(identity);
const CloseEditionDistributorTokenAccountAccounts = ((_j = ixMap.closeEditionDistributorTokenAccount) !== null && _j !== void 0 ? _j : []).map(identity);
const CreateAuctionHouseAccounts = ((_k = ixMap.createAuctionHouse) !== null && _k !== void 0 ? _k : []).map(identity);
const CreateEditionDistributorAccounts = ((_l = ixMap.createEditionDistributor) !== null && _l !== void 0 ? _l : []).map(identity);
const CreateLastBidPriceAccounts = ((_m = ixMap.createLastBidPrice) !== null && _m !== void 0 ? _m : []).map(identity);
const CreateTradeStateAccounts = ((_o = ixMap.createTradeState) !== null && _o !== void 0 ? _o : []).map(identity);
const DepositAccounts = ((_p = ixMap.deposit) !== null && _p !== void 0 ? _p : []).map(identity);
const ExecuteSaleV2Accounts = ((_q = ixMap.executeSaleV2) !== null && _q !== void 0 ? _q : []).map(identity);
const SellAccounts = ((_r = ixMap.sell) !== null && _r !== void 0 ? _r : []).map(identity);
const SetEditionDistributorBotProtectionEnabledAccounts = ((_s = ixMap.setEditionDistributorBotProtectionEnabled) !== null && _s !== void 0 ? _s : []).map(identity);
const SetEditionDistributorLimitPerAddressAccounts = ((_t = ixMap.setEditionDistributorLimitPerAddress) !== null && _t !== void 0 ? _t : []).map(identity);
const SetHasBeenSoldAccounts = ((_u = ixMap.setHasBeenSold) !== null && _u !== void 0 ? _u : []).map(identity);
const SetLastBidPriceAccounts = ((_v = ixMap.setLastBidPrice) !== null && _v !== void 0 ? _v : []).map(identity);
const SetPreviousBidderAccounts = ((_w = ixMap.setPreviousBidder) !== null && _w !== void 0 ? _w : []).map(identity);
const SetTickSizeAccounts = ((_x = ixMap.setTickSize) !== null && _x !== void 0 ? _x : []).map(identity);
const ThawDelegatedAccountAccounts = ((_y = ixMap.thawDelegatedAccount) !== null && _y !== void 0 ? _y : []).map(identity);
const UpdateAuctionHouseAccounts = ((_z = ixMap.updateAuctionHouse) !== null && _z !== void 0 ? _z : []).map(identity);
const UpdateEditionDistributorAccounts = ((_0 = ixMap.updateEditionDistributor) !== null && _0 !== void 0 ? _0 : []).map(identity);
const WithdrawAccounts = ((_1 = ixMap.withdraw) !== null && _1 !== void 0 ? _1 : []).map(identity);
const WithdrawBonkAccounts = ((_2 = ixMap.withdrawBonk) !== null && _2 !== void 0 ? _2 : []).map(identity);
const WithdrawFromFeeAccounts = ((_3 = ixMap.withdrawFromFee) !== null && _3 !== void 0 ? _3 : []).map(identity);
const WithdrawFromTreasuryAccounts = ((_4 = ixMap.withdrawFromTreasury) !== null && _4 !== void 0 ? _4 : []).map(identity);
